---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netbird.management.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
