---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.management.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "netbird.management.matchLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      appProtocol: kubernetes.io/h2c
    - name: grpc
      port: 33073
      targetPort: grpc
      appProtocol: kubernetes.io/h2c
    - name: metrics
      port: 9090
      targetPort: metrics
